# Use the official NGINX image
FROM nginx:latest

# Copy the custom NGINX configuration into the container
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy frontend build files into the NGINX web root
COPY ./frontend/app/build /usr/share/nginx/html

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start NGINX in the foreground #
CMD ["nginx", "-g", "daemon off;"]
